// AUTO-GENERATED by build_course_plan.js -- do not edit by hand.
// 120 classes | 301 ayat | 2070 words
module.exports = {
 "weeks": 24,
 "classesPerWeek": 5,
 "classes": [
  {
   "index": 1,
   "week": 1,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "fatiha",
   "passageName": "সূরা আল-ফাতিহা",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "1:1",
    "1:2",
    "1:3",
    "1:4"
   ],
   "passages": [
    "fatiha"
   ],
   "words": 13
  },
  {
   "index": 2,
   "week": 1,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "fatiha",
   "passageName": "সূরা আল-ফাতিহা",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "1:5",
    "1:6",
    "1:7"
   ],
   "passages": [
    "fatiha"
   ],
   "words": 16
  },
  {
   "index": 3,
   "week": 1,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s112",
   "passageName": "সূরা আল-ইখলাস",
   "part": null,
   "ayat": [
    "112:1",
    "112:2",
    "112:3",
    "112:4"
   ],
   "passages": [
    "s112"
   ],
   "words": 15
  },
  {
   "index": 4,
   "week": 1,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s113",
   "passageName": "সূরা আল-ফালাক",
   "part": null,
   "ayat": [
    "113:1",
    "113:2",
    "113:3",
    "113:4",
    "113:5"
   ],
   "passages": [
    "s113"
   ],
   "words": 23
  },
  {
   "index": 5,
   "week": 1,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    1
   ]
  },
  {
   "index": 6,
   "week": 2,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s114",
   "passageName": "সূরা আন-নাস",
   "part": null,
   "ayat": [
    "114:1",
    "114:2",
    "114:3",
    "114:4",
    "114:5",
    "114:6"
   ],
   "passages": [
    "s114"
   ],
   "words": 20
  },
  {
   "index": 7,
   "week": 2,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s108",
   "passageName": "সূরা আল-কাওসার",
   "part": null,
   "ayat": [
    "108:1",
    "108:2",
    "108:3"
   ],
   "passages": [
    "s108"
   ],
   "words": 10
  },
  {
   "index": 8,
   "week": 2,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s103",
   "passageName": "সূরা আল-আসর",
   "part": null,
   "ayat": [
    "103:1",
    "103:2",
    "103:3"
   ],
   "passages": [
    "s103"
   ],
   "words": 14
  },
  {
   "index": 9,
   "week": 2,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s110",
   "passageName": "সূরা আন-নাসর",
   "part": null,
   "ayat": [
    "110:1",
    "110:2",
    "110:3"
   ],
   "passages": [
    "s110"
   ],
   "words": 19
  },
  {
   "index": 10,
   "week": 2,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    2,
    1
   ]
  },
  {
   "index": 11,
   "week": 3,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s109",
   "passageName": "সূরা আল-কাফিরুন",
   "part": null,
   "ayat": [
    "109:1",
    "109:2",
    "109:3",
    "109:4",
    "109:5",
    "109:6"
   ],
   "passages": [
    "s109"
   ],
   "words": 26
  },
  {
   "index": 12,
   "week": 3,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s111",
   "passageName": "সূরা আল-মাসাদ",
   "part": null,
   "ayat": [
    "111:1",
    "111:2",
    "111:3",
    "111:4",
    "111:5"
   ],
   "passages": [
    "s111"
   ],
   "words": 23
  },
  {
   "index": 13,
   "week": 3,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s105",
   "passageName": "সূরা আল-ফিল",
   "part": null,
   "ayat": [
    "105:1",
    "105:2",
    "105:3",
    "105:4",
    "105:5"
   ],
   "passages": [
    "s105"
   ],
   "words": 23
  },
  {
   "index": 14,
   "week": 3,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s106",
   "passageName": "সূরা কুরাইশ",
   "part": null,
   "ayat": [
    "106:1",
    "106:2",
    "106:3",
    "106:4"
   ],
   "passages": [
    "s106"
   ],
   "words": 17
  },
  {
   "index": 15,
   "week": 3,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    3,
    2
   ]
  },
  {
   "index": 16,
   "week": 4,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s107",
   "passageName": "সূরা আল-মাউন",
   "part": null,
   "ayat": [
    "107:1",
    "107:2",
    "107:3",
    "107:4",
    "107:5",
    "107:6",
    "107:7"
   ],
   "passages": [
    "s107"
   ],
   "words": 25
  },
  {
   "index": 17,
   "week": 4,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s104",
   "passageName": "সূরা আল-হুমাযাহ",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "104:1",
    "104:2",
    "104:3",
    "104:4",
    "104:5"
   ],
   "passages": [
    "s104"
   ],
   "words": 20
  },
  {
   "index": 18,
   "week": 4,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s104",
   "passageName": "সূরা আল-হুমাযাহ",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "104:6",
    "104:7",
    "104:8",
    "104:9"
   ],
   "passages": [
    "s104"
   ],
   "words": 13
  },
  {
   "index": 19,
   "week": 4,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s99",
   "passageName": "সূরা আয-যালযালাহ",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "99:1",
    "99:2",
    "99:3",
    "99:4"
   ],
   "passages": [
    "s99"
   ],
   "words": 14
  },
  {
   "index": 20,
   "week": 4,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    4,
    3,
    1
   ]
  },
  {
   "index": 21,
   "week": 5,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s99",
   "passageName": "সূরা আয-যালযালাহ",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "99:5",
    "99:6",
    "99:7",
    "99:8"
   ],
   "passages": [
    "s99"
   ],
   "words": 22
  },
  {
   "index": 22,
   "week": 5,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s100",
   "passageName": "সূরা আল-আদিয়াত",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "100:1",
    "100:2",
    "100:3",
    "100:4",
    "100:5",
    "100:6"
   ],
   "passages": [
    "s100"
   ],
   "words": 16
  },
  {
   "index": 23,
   "week": 5,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s100",
   "passageName": "সূরা আল-আদিয়াত",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "100:7",
    "100:8",
    "100:9",
    "100:10",
    "100:11"
   ],
   "passages": [
    "s100"
   ],
   "words": 24
  },
  {
   "index": 24,
   "week": 5,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s101",
   "passageName": "সূরা আল-ক্বারিআহ",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "101:1",
    "101:2",
    "101:3",
    "101:4",
    "101:5",
    "101:6"
   ],
   "passages": [
    "s101"
   ],
   "words": 20
  },
  {
   "index": 25,
   "week": 5,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    5,
    4,
    2
   ]
  },
  {
   "index": 26,
   "week": 6,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s101",
   "passageName": "সূরা আল-ক্বারিআহ",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "101:7",
    "101:8",
    "101:9",
    "101:10",
    "101:11"
   ],
   "passages": [
    "s101"
   ],
   "words": 16
  },
  {
   "index": 27,
   "week": 6,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s102",
   "passageName": "সূরা আত-তাকাসুর",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "102:1",
    "102:2",
    "102:3",
    "102:4"
   ],
   "passages": [
    "s102"
   ],
   "words": 12
  },
  {
   "index": 28,
   "week": 6,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s102",
   "passageName": "সূরা আত-তাকাসুর",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "102:5",
    "102:6",
    "102:7",
    "102:8"
   ],
   "passages": [
    "s102"
   ],
   "words": 16
  },
  {
   "index": 29,
   "week": 6,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s97",
   "passageName": "সূরা আল-কদর",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "97:1",
    "97:2",
    "97:3"
   ],
   "passages": [
    "s97"
   ],
   "words": 16
  },
  {
   "index": 30,
   "week": 6,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    6,
    5,
    3
   ]
  },
  {
   "index": 31,
   "week": 7,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s97",
   "passageName": "সূরা আল-কদর",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "97:4",
    "97:5"
   ],
   "passages": [
    "s97"
   ],
   "words": 14
  },
  {
   "index": 32,
   "week": 7,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s95",
   "passageName": "সূরা আত-তীন",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "95:1",
    "95:2",
    "95:3",
    "95:4"
   ],
   "passages": [
    "s95"
   ],
   "words": 13
  },
  {
   "index": 33,
   "week": 7,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s95",
   "passageName": "সূরা আত-তীন",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "95:5",
    "95:6",
    "95:7",
    "95:8"
   ],
   "passages": [
    "s95"
   ],
   "words": 21
  },
  {
   "index": 34,
   "week": 7,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s94",
   "passageName": "সূরা আশ-শারহ",
   "part": null,
   "ayat": [
    "94:1",
    "94:2",
    "94:3",
    "94:4",
    "94:5",
    "94:6",
    "94:7",
    "94:8"
   ],
   "passages": [
    "s94"
   ],
   "words": 27
  },
  {
   "index": 35,
   "week": 7,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    7,
    6,
    4
   ]
  },
  {
   "index": 36,
   "week": 8,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s93",
   "passageName": "সূরা আদ-দুহা",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "93:1",
    "93:2",
    "93:3",
    "93:4",
    "93:5",
    "93:6"
   ],
   "passages": [
    "s93"
   ],
   "words": 22
  },
  {
   "index": 37,
   "week": 8,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s93",
   "passageName": "সূরা আদ-দুহা",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "93:7",
    "93:8",
    "93:9",
    "93:10",
    "93:11"
   ],
   "passages": [
    "s93"
   ],
   "words": 18
  },
  {
   "index": 38,
   "week": 8,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s96",
   "passageName": "সূরা আল-আলাক",
   "part": {
    "k": 1,
    "of": 5
   },
   "ayat": [
    "96:1",
    "96:2",
    "96:3",
    "96:4"
   ],
   "passages": [
    "s96"
   ],
   "words": 15
  },
  {
   "index": 39,
   "week": 8,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s96",
   "passageName": "সূরা আল-আলাক",
   "part": {
    "k": 2,
    "of": 5
   },
   "ayat": [
    "96:5",
    "96:6",
    "96:7",
    "96:8"
   ],
   "passages": [
    "s96"
   ],
   "words": 16
  },
  {
   "index": 40,
   "week": 8,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    8,
    7,
    5,
    1
   ]
  },
  {
   "index": 41,
   "week": 9,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s96",
   "passageName": "সূরা আল-আলাক",
   "part": {
    "k": 3,
    "of": 5
   },
   "ayat": [
    "96:9",
    "96:10",
    "96:11"
   ],
   "passages": [
    "s96"
   ],
   "words": 11
  },
  {
   "index": 42,
   "week": 9,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s96",
   "passageName": "সূরা আল-আলাক",
   "part": {
    "k": 4,
    "of": 5
   },
   "ayat": [
    "96:12",
    "96:13",
    "96:14",
    "96:15"
   ],
   "passages": [
    "s96"
   ],
   "words": 18
  },
  {
   "index": 43,
   "week": 9,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s96",
   "passageName": "সূরা আল-আলাক",
   "part": {
    "k": 5,
    "of": 5
   },
   "ayat": [
    "96:16",
    "96:17",
    "96:18",
    "96:19"
   ],
   "passages": [
    "s96"
   ],
   "words": 12
  },
  {
   "index": 44,
   "week": 9,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s91",
   "passageName": "সূরা আশ-শামস",
   "part": {
    "k": 1,
    "of": 3
   },
   "ayat": [
    "91:1",
    "91:2",
    "91:3",
    "91:4",
    "91:5"
   ],
   "passages": [
    "s91"
   ],
   "words": 14
  },
  {
   "index": 45,
   "week": 9,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    9,
    8,
    6,
    2
   ]
  },
  {
   "index": 46,
   "week": 10,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s91",
   "passageName": "সূরা আশ-শামস",
   "part": {
    "k": 2,
    "of": 3
   },
   "ayat": [
    "91:6",
    "91:7",
    "91:8",
    "91:9",
    "91:10"
   ],
   "passages": [
    "s91"
   ],
   "words": 17
  },
  {
   "index": 47,
   "week": 10,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s91",
   "passageName": "সূরা আশ-শামস",
   "part": {
    "k": 3,
    "of": 3
   },
   "ayat": [
    "91:11",
    "91:12",
    "91:13",
    "91:14",
    "91:15"
   ],
   "passages": [
    "s91"
   ],
   "words": 23
  },
  {
   "index": 48,
   "week": 10,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s92",
   "passageName": "সূরা আল-লাইল",
   "part": {
    "k": 1,
    "of": 4
   },
   "ayat": [
    "92:1",
    "92:2",
    "92:3",
    "92:4",
    "92:5"
   ],
   "passages": [
    "s92"
   ],
   "words": 17
  },
  {
   "index": 49,
   "week": 10,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s92",
   "passageName": "সূরা আল-লাইল",
   "part": {
    "k": 2,
    "of": 4
   },
   "ayat": [
    "92:6",
    "92:7",
    "92:8",
    "92:9",
    "92:10",
    "92:11"
   ],
   "passages": [
    "s92"
   ],
   "words": 18
  },
  {
   "index": 50,
   "week": 10,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    10,
    9,
    7,
    3
   ]
  },
  {
   "index": 51,
   "week": 11,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s92",
   "passageName": "সূরা আল-লাইল",
   "part": {
    "k": 3,
    "of": 4
   },
   "ayat": [
    "92:12",
    "92:13",
    "92:14",
    "92:15",
    "92:16"
   ],
   "passages": [
    "s92"
   ],
   "words": 17
  },
  {
   "index": 52,
   "week": 11,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s92",
   "passageName": "সূরা আল-লাইল",
   "part": {
    "k": 4,
    "of": 4
   },
   "ayat": [
    "92:17",
    "92:18",
    "92:19",
    "92:20",
    "92:21"
   ],
   "passages": [
    "s92"
   ],
   "words": 19
  },
  {
   "index": 53,
   "week": 11,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s98",
   "passageName": "সূরা আল-বাইয়্যিনাহ",
   "part": {
    "k": 1,
    "of": 5
   },
   "ayat": [
    "98:1",
    "98:2"
   ],
   "passages": [
    "s98"
   ],
   "words": 18
  },
  {
   "index": 54,
   "week": 11,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "s98",
   "passageName": "সূরা আল-বাইয়্যিনাহ",
   "part": {
    "k": 2,
    "of": 5
   },
   "ayat": [
    "98:3"
   ],
   "passages": [
    "s98"
   ],
   "words": 3
  },
  {
   "index": 55,
   "week": 11,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    11,
    10,
    8,
    4
   ]
  },
  {
   "index": 56,
   "week": 12,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "s98",
   "passageName": "সূরা আল-বাইয়্যিনাহ",
   "part": {
    "k": 3,
    "of": 5
   },
   "ayat": [
    "98:4",
    "98:5"
   ],
   "passages": [
    "s98"
   ],
   "words": 27
  },
  {
   "index": 57,
   "week": 12,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "s98",
   "passageName": "সূরা আল-বাইয়্যিনাহ",
   "part": {
    "k": 4,
    "of": 5
   },
   "ayat": [
    "98:6"
   ],
   "passages": [
    "s98"
   ],
   "words": 16
  },
  {
   "index": 58,
   "week": 12,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "s98",
   "passageName": "সূরা আল-বাইয়্যিনাহ",
   "part": {
    "k": 5,
    "of": 5
   },
   "ayat": [
    "98:7",
    "98:8"
   ],
   "passages": [
    "s98"
   ],
   "words": 30
  },
  {
   "index": 59,
   "week": 12,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "baqarah_1_5",
   "passageName": "সূরা আল-বাকারাহ (১-৫)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "2:1",
    "2:2",
    "2:3"
   ],
   "passages": [
    "baqarah_1_5"
   ],
   "words": 16
  },
  {
   "index": 60,
   "week": 12,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    12,
    11,
    9,
    5
   ]
  },
  {
   "index": 61,
   "week": 13,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "baqarah_1_5",
   "passageName": "সূরা আল-বাকারাহ (১-৫)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "2:4",
    "2:5"
   ],
   "passages": [
    "baqarah_1_5"
   ],
   "words": 20
  },
  {
   "index": 62,
   "week": 13,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "baqarah_163",
   "passageName": "সূরা আল-বাকারাহ (১৬৩)",
   "part": null,
   "ayat": [
    "2:163"
   ],
   "passages": [
    "baqarah_163"
   ],
   "words": 9
  },
  {
   "index": 63,
   "week": 13,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "jinn_1_4",
   "passageName": "সূরা আল-জিন (১-৪)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "72:1",
    "72:2"
   ],
   "passages": [
    "jinn_1_4"
   ],
   "words": 22
  },
  {
   "index": 64,
   "week": 13,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "jinn_1_4",
   "passageName": "সূরা আল-জিন (১-৪)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "72:3",
    "72:4"
   ],
   "passages": [
    "jinn_1_4"
   ],
   "words": 16
  },
  {
   "index": 65,
   "week": 13,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    13,
    12,
    10,
    6
   ]
  },
  {
   "index": 66,
   "week": 14,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "saffat_1_11",
   "passageName": "সূরা আস-সাফফাত (১-১১)",
   "part": {
    "k": 1,
    "of": 3
   },
   "ayat": [
    "37:1",
    "37:2",
    "37:3",
    "37:4"
   ],
   "passages": [
    "saffat_1_11"
   ],
   "words": 9
  },
  {
   "index": 67,
   "week": 14,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "saffat_1_11",
   "passageName": "সূরা আস-সাফফাত (১-১১)",
   "part": {
    "k": 2,
    "of": 3
   },
   "ayat": [
    "37:5",
    "37:6",
    "37:7"
   ],
   "passages": [
    "saffat_1_11"
   ],
   "words": 18
  },
  {
   "index": 68,
   "week": 14,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "saffat_1_11",
   "passageName": "সূরা আস-সাফফাত (১-১১)",
   "part": {
    "k": 3,
    "of": 3
   },
   "ayat": [
    "37:8",
    "37:9",
    "37:10",
    "37:11"
   ],
   "passages": [
    "saffat_1_11"
   ],
   "words": 32
  },
  {
   "index": 69,
   "week": 14,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "rahman_33_40",
   "passageName": "সূরা আর-রহমান (৩৩-৪০)",
   "part": {
    "k": 1,
    "of": 3
   },
   "ayat": [
    "55:33",
    "55:34",
    "55:35"
   ],
   "passages": [
    "rahman_33_40"
   ],
   "words": 28
  },
  {
   "index": 70,
   "week": 14,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    14,
    13,
    11,
    7
   ]
  },
  {
   "index": 71,
   "week": 15,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "rahman_33_40",
   "passageName": "সূরা আর-রহমান (৩৩-৪০)",
   "part": {
    "k": 2,
    "of": 3
   },
   "ayat": [
    "55:36",
    "55:37"
   ],
   "passages": [
    "rahman_33_40"
   ],
   "words": 10
  },
  {
   "index": 72,
   "week": 15,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "rahman_33_40",
   "passageName": "সূরা আর-রহমান (৩৩-৪০)",
   "part": {
    "k": 3,
    "of": 3
   },
   "ayat": [
    "55:38",
    "55:39",
    "55:40"
   ],
   "passages": [
    "rahman_33_40"
   ],
   "words": 16
  },
  {
   "index": 73,
   "week": 15,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 1,
    "of": 15
   },
   "ayat": [
    "67:1",
    "67:2"
   ],
   "passages": [
    "mulk"
   ],
   "words": 20
  },
  {
   "index": 74,
   "week": 15,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 2,
    "of": 15
   },
   "ayat": [
    "67:3",
    "67:4"
   ],
   "passages": [
    "mulk"
   ],
   "words": 28
  },
  {
   "index": 75,
   "week": 15,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    15,
    14,
    12,
    8
   ]
  },
  {
   "index": 76,
   "week": 16,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 3,
    "of": 15
   },
   "ayat": [
    "67:5",
    "67:6"
   ],
   "passages": [
    "mulk"
   ],
   "words": 19
  },
  {
   "index": 77,
   "week": 16,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 4,
    "of": 15
   },
   "ayat": [
    "67:7",
    "67:8"
   ],
   "passages": [
    "mulk"
   ],
   "words": 21
  },
  {
   "index": 78,
   "week": 16,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 5,
    "of": 15
   },
   "ayat": [
    "67:9",
    "67:10"
   ],
   "passages": [
    "mulk"
   ],
   "words": 29
  },
  {
   "index": 79,
   "week": 16,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 6,
    "of": 15
   },
   "ayat": [
    "67:11",
    "67:12"
   ],
   "passages": [
    "mulk"
   ],
   "words": 14
  },
  {
   "index": 80,
   "week": 16,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    16,
    15,
    13,
    9
   ]
  },
  {
   "index": 81,
   "week": 17,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 7,
    "of": 15
   },
   "ayat": [
    "67:13",
    "67:14"
   ],
   "passages": [
    "mulk"
   ],
   "words": 16
  },
  {
   "index": 82,
   "week": 17,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 8,
    "of": 15
   },
   "ayat": [
    "67:15",
    "67:16"
   ],
   "passages": [
    "mulk"
   ],
   "words": 25
  },
  {
   "index": 83,
   "week": 17,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 9,
    "of": 15
   },
   "ayat": [
    "67:17",
    "67:18"
   ],
   "passages": [
    "mulk"
   ],
   "words": 20
  },
  {
   "index": 84,
   "week": 17,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 10,
    "of": 15
   },
   "ayat": [
    "67:19",
    "67:20"
   ],
   "passages": [
    "mulk"
   ],
   "words": 30
  },
  {
   "index": 85,
   "week": 17,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    17,
    16,
    14,
    10
   ]
  },
  {
   "index": 86,
   "week": 18,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 11,
    "of": 15
   },
   "ayat": [
    "67:21",
    "67:22"
   ],
   "passages": [
    "mulk"
   ],
   "words": 24
  },
  {
   "index": 87,
   "week": 18,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 12,
    "of": 15
   },
   "ayat": [
    "67:23",
    "67:24"
   ],
   "passages": [
    "mulk"
   ],
   "words": 20
  },
  {
   "index": 88,
   "week": 18,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 13,
    "of": 15
   },
   "ayat": [
    "67:25",
    "67:26"
   ],
   "passages": [
    "mulk"
   ],
   "words": 16
  },
  {
   "index": 89,
   "week": 18,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 14,
    "of": 15
   },
   "ayat": [
    "67:27",
    "67:28"
   ],
   "passages": [
    "mulk"
   ],
   "words": 28
  },
  {
   "index": 90,
   "week": 18,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    18,
    17,
    15,
    11
   ]
  },
  {
   "index": 91,
   "week": 19,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "mulk",
   "passageName": "সূরা আল-মূলক",
   "part": {
    "k": 15,
    "of": 15
   },
   "ayat": [
    "67:29",
    "67:30"
   ],
   "passages": [
    "mulk"
   ],
   "words": 23
  },
  {
   "index": 92,
   "week": 19,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "ayatul_kursi",
   "passageName": "আয়াতুল কুরসি",
   "part": null,
   "ayat": [
    "2:255"
   ],
   "passages": [
    "ayatul_kursi"
   ],
   "words": 50
  },
  {
   "index": 93,
   "week": 19,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "baqarah_256_257",
   "passageName": "সূরা আল-বাকারাহ (২৫৬-২৫৭)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "2:256"
   ],
   "passages": [
    "baqarah_256_257"
   ],
   "words": 24
  },
  {
   "index": 94,
   "week": 19,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "baqarah_256_257",
   "passageName": "সূরা আল-বাকারাহ (২৫৬-২৫৭)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "2:257"
   ],
   "passages": [
    "baqarah_256_257"
   ],
   "words": 24
  },
  {
   "index": 95,
   "week": 19,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    19,
    18,
    16,
    12
   ]
  },
  {
   "index": 96,
   "week": 20,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "imran_18",
   "passageName": "সূরা আলে-ইমরান (১৮)",
   "part": null,
   "ayat": [
    "3:18"
   ],
   "passages": [
    "imran_18"
   ],
   "words": 18
  },
  {
   "index": 97,
   "week": 20,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "imran_26_27",
   "passageName": "সূরা আলে-ইমরান (২৬-২৭)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "3:26"
   ],
   "passages": [
    "imran_26_27"
   ],
   "words": 25
  },
  {
   "index": 98,
   "week": 20,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "imran_26_27",
   "passageName": "সূরা আলে-ইমরান (২৬-২৭)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "3:27"
   ],
   "passages": [
    "imran_26_27"
   ],
   "words": 21
  },
  {
   "index": 99,
   "week": 20,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "araf_54_56",
   "passageName": "সূরা আল-আরাফ (৫৪-৫৬)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "7:54",
    "7:55"
   ],
   "passages": [
    "araf_54_56"
   ],
   "words": 40
  },
  {
   "index": 100,
   "week": 20,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    20,
    19,
    17,
    13
   ]
  },
  {
   "index": 101,
   "week": 21,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "araf_54_56",
   "passageName": "সূরা আল-আরাফ (৫৪-৫৬)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "7:56"
   ],
   "passages": [
    "araf_54_56"
   ],
   "words": 15
  },
  {
   "index": 102,
   "week": 21,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "isra_110_111",
   "passageName": "সূরা বনী ইসরাইল (১১০-১১১)",
   "part": null,
   "ayat": [
    "17:110",
    "17:111"
   ],
   "passages": [
    "isra_110_111"
   ],
   "words": 43
  },
  {
   "index": 103,
   "week": 21,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "muminun_115_118",
   "passageName": "সূরা আল-মুমিনুন (১১৫-১১৮)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "23:115",
    "23:116"
   ],
   "passages": [
    "muminun_115_118"
   ],
   "words": 19
  },
  {
   "index": 104,
   "week": 21,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "muminun_115_118",
   "passageName": "সূরা আল-মুমিনুন (১১৫-১১৮)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "23:117",
    "23:118"
   ],
   "passages": [
    "muminun_115_118"
   ],
   "words": 25
  },
  {
   "index": 105,
   "week": 21,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    21,
    20,
    18,
    14
   ]
  },
  {
   "index": 106,
   "week": 22,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "hashr_21_24",
   "passageName": "সূরা আল-হাশর (২১-২৪)",
   "part": {
    "k": 1,
    "of": 2
   },
   "ayat": [
    "59:21",
    "59:22"
   ],
   "passages": [
    "hashr_21_24"
   ],
   "words": 31
  },
  {
   "index": 107,
   "week": 22,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "hashr_21_24",
   "passageName": "সূরা আল-হাশর (২১-২৪)",
   "part": {
    "k": 2,
    "of": 2
   },
   "ayat": [
    "59:23",
    "59:24"
   ],
   "passages": [
    "hashr_21_24"
   ],
   "words": 36
  },
  {
   "index": 108,
   "week": 22,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "baqarah_284_286",
   "passageName": "সূরা আল-বাকারাহ (২৮৪-২৮৬)",
   "part": {
    "k": 1,
    "of": 3
   },
   "ayat": [
    "2:284"
   ],
   "passages": [
    "baqarah_284_286"
   ],
   "words": 28
  },
  {
   "index": 109,
   "week": 22,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "baqarah_284_286",
   "passageName": "সূরা আল-বাকারাহ (২৮৪-২৮৬)",
   "part": {
    "k": 2,
    "of": 3
   },
   "ayat": [
    "2:285"
   ],
   "passages": [
    "baqarah_284_286"
   ],
   "words": 27
  },
  {
   "index": 110,
   "week": 22,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    22,
    21,
    19,
    15
   ]
  },
  {
   "index": 111,
   "week": 23,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "baqarah_284_286",
   "passageName": "সূরা আল-বাকারাহ (২৮৪-২৮৬)",
   "part": {
    "k": 3,
    "of": 3
   },
   "ayat": [
    "2:286"
   ],
   "passages": [
    "baqarah_284_286"
   ],
   "words": 49
  },
  {
   "index": 112,
   "week": 23,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "kahf_first10",
   "passageName": "সূরা আল-কাহফ (প্রথম ১০)",
   "part": {
    "k": 1,
    "of": 3
   },
   "ayat": [
    "18:1",
    "18:2",
    "18:3"
   ],
   "passages": [
    "kahf_first10"
   ],
   "words": 29
  },
  {
   "index": 113,
   "week": 23,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "kahf_first10",
   "passageName": "সূরা আল-কাহফ (প্রথম ১০)",
   "part": {
    "k": 2,
    "of": 3
   },
   "ayat": [
    "18:4",
    "18:5",
    "18:6",
    "18:7"
   ],
   "passages": [
    "kahf_first10"
   ],
   "words": 44
  },
  {
   "index": 114,
   "week": 23,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "kahf_first10",
   "passageName": "সূরা আল-কাহফ (প্রথম ১০)",
   "part": {
    "k": 3,
    "of": 3
   },
   "ayat": [
    "18:8",
    "18:9",
    "18:10"
   ],
   "passages": [
    "kahf_first10"
   ],
   "words": 32
  },
  {
   "index": 115,
   "week": 23,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    23,
    22,
    20,
    16
   ]
  },
  {
   "index": 116,
   "week": 24,
   "classInWeek": 1,
   "type": "lesson",
   "passageId": "kahf_last10",
   "passageName": "সূরা আল-কাহফ (শেষ ১০)",
   "part": {
    "k": 1,
    "of": 4
   },
   "ayat": [
    "18:101",
    "18:102",
    "18:103"
   ],
   "passages": [
    "kahf_last10"
   ],
   "words": 30
  },
  {
   "index": 117,
   "week": 24,
   "classInWeek": 2,
   "type": "lesson",
   "passageId": "kahf_last10",
   "passageName": "সূরা আল-কাহফ (শেষ ১০)",
   "part": {
    "k": 2,
    "of": 4
   },
   "ayat": [
    "18:104",
    "18:105"
   ],
   "passages": [
    "kahf_last10"
   ],
   "words": 25
  },
  {
   "index": 118,
   "week": 24,
   "classInWeek": 3,
   "type": "lesson",
   "passageId": "kahf_last10",
   "passageName": "সূরা আল-কাহফ (শেষ ১০)",
   "part": {
    "k": 3,
    "of": 4
   },
   "ayat": [
    "18:106",
    "18:107",
    "18:108"
   ],
   "passages": [
    "kahf_last10"
   ],
   "words": 25
  },
  {
   "index": 119,
   "week": 24,
   "classInWeek": 4,
   "type": "lesson",
   "passageId": "kahf_last10",
   "passageName": "সূরা আল-কাহফ (শেষ ১০)",
   "part": {
    "k": 4,
    "of": 4
   },
   "ayat": [
    "18:109",
    "18:110"
   ],
   "passages": [
    "kahf_last10"
   ],
   "words": 42
  },
  {
   "index": 120,
   "week": 24,
   "classInWeek": 5,
   "type": "revision",
   "ayat": [],
   "passages": [],
   "words": 0,
   "reviewWeeks": [
    24,
    23,
    21,
    17
   ]
  }
 ]
};
